// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI commands (migrate, studio, etc.) need a non-pooled connection;
    // the app's runtime PrismaClient uses DATABASE_URL (the pgbouncer pooler) instead — see src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
